server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
    location /executive.html {
        try_files $uri =404;
    }
    location /kiosk.html {
        try_files $uri =404;
    }
}
